import { Class } from '@/features/classes/types';

export const mockClasses: Class[] = [
  {
    id: '1',
    name: 'Mathematics 101',
    description: 'Introduction to basic mathematical concepts',
    subject: 'Mathematics',
    teacherId: '2',
    teacherName: 'John Smith',
    teacherEmail: 'teacher@smartlearner.com',
    schedule: 'Mon/Wed 10:00 AM',
    room: '204',
    capacity: 30,
    createdAt: '2024-03-20T10:00:00Z',
    updatedAt: '2024-03-20T10:00:00Z',
  },
  {
    id: '2',
    name: 'Physics Fundamentals',
    description: 'Basic principles of physics and mechanics',
    subject: 'Physics',
    teacherId: '2',
    teacherName: 'John Smith',
    teacherEmail: 'teacher@smartlearner.com',
    schedule: 'Tue/Thu 11:00 AM',
    room: '305',
    capacity: 25,
    createdAt: '2024-03-20T10:00:00Z',
    updatedAt: '2024-03-20T10:00:00Z',
  },
  {
    id: '3',
    name: 'English Literature',
    description: 'Analysis of classic literary works',
    subject: 'English',
    teacherId: '2',
    teacherName: 'John Smith',
    teacherEmail: 'teacher@smartlearner.com',
    schedule: 'Mon/Wed 2:00 PM',
    room: '101',
    capacity: 35,
    createdAt: '2024-03-20T10:00:00Z',
    updatedAt: '2024-03-20T10:00:00Z',
  },
];