import { Student } from '@/features/students/types';

export const mockStudents: Student[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    studentId: 'STU001',
    gender: 'male',
    dateOfBirth: '2006-05-15',
    grade: '10th',
    parentName: 'Jane Doe',
    parentEmail: 'jane.doe@example.com',
    phone: '123-456-7890',
    address: '123 Main St',
    enrollmentDate: '2022-09-01',
    status: 'active',
  },
  {
    id: '2',
    name: 'Sarah Smith',
    email: 'sarah.smith@example.com',
    studentId: 'STU002',
    gender: 'female',
    dateOfBirth: '2006-08-20',
    grade: '10th',
    parentName: 'Michael Smith',
    parentEmail: 'michael.smith@example.com',
    phone: '123-456-7891',
    address: '456 Oak St',
    enrollmentDate: '2022-09-01',
    status: 'active',
  },
  {
    id: '3',
    name: 'David Johnson',
    email: 'david.johnson@example.com',
    studentId: 'STU003',
    gender: 'male',
    dateOfBirth: '2006-03-10',
    grade: '10th',
    parentName: 'Lisa Johnson',
    parentEmail: 'lisa.johnson@example.com',
    phone: '123-456-7892',
    address: '789 Pine St',
    enrollmentDate: '2022-09-01',
    status: 'active',
  },
];